FichaMedica/FichaMedica/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings

from core import views
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('account.urls')),
    path('persona/', include('persona.urls')),
 
    path('registro-medico/', include('RegistroMedico.urls')), 
    path('medico/', include('Medico.urls')),
    path('Representate/', include('Representate.urls')),
   
    
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FichaMedica/Medico/urls.py
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('medico_home/', MedicoHomeView.as_view(), name='medico_home'),
     # Ruta para el formulario Electro Basal
    path('electro_basal/<int:jugador_id>/', views.electro_basal_view, name='electro_basal_view'),

    # Ruta para el formulario Electro Esfuerzo
    path('electro_esfuerzo/<int:jugador_id>/', views.electro_esfuerzo_view, name='electro_esfuerzo_view'),

    # Ruta para el formulario Cardiovascular
    path('cardiovascular/<int:jugador_id>/', views.cardiovascular_view, name='cardiovascular_view'),

    # Ruta para el formulario Laboratorio
    path('laboratorio/<int:jugador_id>/', views.laboratorio_view, name='laboratorio_view'),

    # Ruta para el formulario Torax
    path('torax/<int:jugador_id>/', views.torax_view, name='torax_view'),

    # Ruta para el formulario Oftalmológico
    path('oftalmologico/<int:jugador_id>/', views.oftalmologico_view, name='oftalmologico_view'),
    
    # Ruta para el formulario de Registo medico
    path('registro_medico_update/<int:jugador_id>/', views.registro_medico_update_view, name='registro_medico_update_view'),

    path('ficha_medica/<int:jugador_id>/', views.ficha_medica_views, name='ficha_medica'),

]

FichaMedica/RegistroMedico/urls.py
from django.urls import path
from .views import *

app_name = 'registroMedico'

urlpatterns = [
    # crud antecedentes medicos 
    path('cargar_antecedente/<int:jugador_id>/', CargarAntecedenteView.as_view(), name='cargar_antecedente'),
    path('ver_antecedente/<int:jugador_id>/', VerAntecedenteView.as_view(), name='ver_antecedente'),
    path('modificar_antecedente/<int:antecedente_id>/', ModificarAntecedenteView.as_view(), name='modificar_antecedente'),
    path('actualizar_consentimiento/<int:pk>/', ActualizarConsentimientoView.as_view(), name='consentimiento'),
    # crud estudios medicos 
    path('cargar_estudio/<int:ficha_id>/', CargarEstudioView.as_view(), name='cargar_estudio'),
    path('ficha/<int:ficha_medica_id>/estudios/', EstudiosMedicoListView.as_view(), name='ver_estudios'),
    path('estudio/<int:pk>/eliminar/', EliminarEstudioView.as_view(), name='eliminar_estudio'),  
    path('estudio/<int:pk>/eliminar/medico/', EliminarEstudioMedicoView.as_view(), name='eliminar_estudio_medico'),
    
]

FichaMedica/persona/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('registrar/', views.registrar_persona, name='registrar_persona'),  # URL para registrar persona
    #path('seleccionar_torneo_categoria/', seleccionar_torneo_categoria, name='seleccionar_torneo_categoria'),
   # URL para la vista del jugador
    path('rerror_registro/', views.error_registro, name='rerror_registro'),
    path('seleccionar_categoria_equipo/', views.seleccionar_categoria_equipo, name='seleccionar_categoria_equipo'),
    path('fetch_categorias/<int:torneo_id>/', views.fetch_categorias, name='fetch_categorias'),
    path('fetch_equipos/<int:categoria_id>/', views.fetch_equipos, name='fetch_equipos'),
    path('menu_jugador/', views.menu_jugador, name='menu_jugador'),
    path('perfil/', views.perfil, name='perfil'),
     # URL para cambiar el email
    path('modificar_email/', views.cambiar_email, name='modificar_email'),

    # URL para cambiar la contraseña
    path('modificar_contrasena/', views.cambiar_contraseña, name='modificar_contrasena'),
   
   
    path('modificar_perfil/', views.modificar_perfil, name='modificar_perfil'),
    
    
]
""" 
 path('seleccionar_torneo/', seleccionar_torneo, name='seleccionar_torneo'),
    path('selecciona_categoria_y_equipo/', seleccionar_categoria_equipo, name='selecciona_categoria_equipo'), """

FichaMedica/persona/models.py
from django.db import models
from account.models import Profile  # Asegúrate de ajustar la ruta según tu estructura

class Persona(models.Model):
    

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=255, blank=True, null=True)
    telefono = models.CharField(max_length=15, blank=True, null=True)
    telefono_alternativo = models.CharField(max_length=15, blank=True, null=True)
   
   

    def __str__(self):
        return f"{self.profile.nombre} {self.profile.apellido}"

class Jugador(models.Model):
    GRUPOS_SANGUINEOS = [
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    ]
    persona = models.OneToOneField(Persona, on_delete=models.CASCADE)
    grupo_sanguineo = models.CharField(max_length=3, choices=GRUPOS_SANGUINEOS, blank=True, null=True)  
    cobertura_medica = models.CharField(max_length=100, blank=True, null=True)
    numero_afiliado = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
       
        return f"{self.persona.profile.nombre} {self.persona.profile.apellido}"

class Torneo(models.Model):
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    descripcion = models.TextField(verbose_name='Descripción',null=True, blank=True)
    direccion = models.CharField(max_length=255, verbose_name='Dirección', null=True, blank=True)
    telefono = models.CharField(max_length=15, verbose_name='Teléfono', null=True, blank=True)
    imagen = models.ImageField(upload_to='imagenes/', null=True, blank=True, verbose_name='Imagen')
    
    def __str__(self):
        return self.nombre


class Categoria(models.Model):
    nombre = models.CharField(max_length=45)
    torneo = models.ForeignKey(Torneo, on_delete=models.CASCADE, related_name='categorias')

    class Meta:
        db_table = 'categorias'  # Nombre de la tabla en la base de datos

    def __str__(self):
        return self.nombre


class Equipo(models.Model):
    nombre = models.CharField(max_length=45)

    class Meta:
        db_table = 'equipo'  # Nombre de la tabla en la base de datos

    def __str__(self):
        return self.nombre


class CategoriaEquipo(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='categoria_equipos')
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE, related_name='categoria_equipos')

    class Meta:
        db_table = 'categoria_equipo'
        unique_together = ('categoria', 'equipo')

    def __str__(self):
        return f"{self.categoria.nombre} - {self.equipo.nombre} - {self.categoria.torneo}"


class JugadorCategoriaEquipo(models.Model):
    jugador = models.ForeignKey(Jugador, on_delete=models.CASCADE)
    categoria_equipo = models.ForeignKey(CategoriaEquipo, on_delete=models.CASCADE, related_name='jugadores')

    class Meta:
        db_table = 'jugador_categoria_equipo'
   
    def __str__(self):
        return f"{self.jugador.persona.profile.nombre} {self.jugador.persona.profile.apellido} - {self.categoria_equipo.equipo.nombre} - {self.categoria_equipo.categoria.nombre} - {self.categoria_equipo.categoria.torneo}"

FichaMedica/persona/views.py
from django.views.decorators.cache import never_cache
from django.contrib import messages
from django.db import IntegrityError
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from RegistroMedico.models import AntecedenteEnfermedades, RegistroMedico


from .forms import *
from .models import *


def registrar_persona(request):
    profile = request.user.profile

    # Intentamos obtener la Persona asociada al profile del usuario
    persona, created = Persona.objects.get_or_create(profile=profile)

    if created:
        print(f"Persona creada: {persona}")
    else:
        print(f"Persona encontrada: {persona}")

    # Verificamos si todos los campos importantes de la persona están completos
    campos_completos = all([
        persona.direccion,
        persona.telefono,
        persona.telefono_alternativo,
    ])

    # Intentamos obtener el jugador asociado a la persona
    try:
        jugador = Jugador.objects.get(persona=persona)
        campos_jugador_completos = all([
            jugador.grupo_sanguineo,
            jugador.cobertura_medica,
            jugador.numero_afiliado,
        ])
    except Jugador.DoesNotExist:
        jugador = None  # Si no hay jugador, se establece en None
        campos_jugador_completos = False

    # Intentamos obtener la relación de equipo y categoría asociada al jugador
    jugador_equipo_categoria = None
    if jugador:
        try:
            jugador_equipo_categoria = JugadorCategoriaEquipo.objects.get(jugador=jugador)
            equipo_categoria_completo = True
        except JugadorCategoriaEquipo.DoesNotExist:
            equipo_categoria_completo = False
    else:
        equipo_categoria_completo = False

    # Verificamos si todos los campos de persona, jugador y equipo-categoría están completos
    if campos_completos and campos_jugador_completos and equipo_categoria_completo:
        return redirect('menu_jugador')

    # Manejo de los formularios
    if request.method == 'POST':
        # Formulario con instancia de persona
        form_persona = PersonaForm(request.POST, instance=persona)
        form_jugador = JugadorForm(request.POST, instance=jugador) if jugador else JugadorForm(request.POST)

        if form_persona.is_valid() and form_jugador.is_valid():
            # Guardar la persona sin crear una nueva si ya existe
            persona_guardada = form_persona.save(commit=False)
            persona_guardada.profile = profile  # Asegurarse de que esté asignado el profile
            persona_guardada.save()  # Aquí se actualiza, no se crea una nueva

            # Guardar el jugador y asignar la persona
            jugador_guardado = form_jugador.save(commit=False)
            jugador_guardado.persona = persona_guardada
            jugador_guardado.save()

            return redirect('seleccionar_categoria_equipo')  # Redirigir al siguiente paso tras guardar
    else:
        form_persona = PersonaForm(instance=persona)
        form_jugador = JugadorForm(instance=jugador) if jugador else JugadorForm()

    context = {
        'form_persona': form_persona,
        'form_jugador': form_jugador,
        'persona': persona,
        'profile': profile,
        'jugador': jugador,
        'jugador_equipo_categoria': jugador_equipo_categoria,  # Añadir jugador_equipo_categoria al contexto
    }
    return render(request, 'persona/registrar_persona.html', context)



def fetch_categorias(request, torneo_id):
    try:
        print(f"Torneo seleccionado: {torneo_id}")
        categorias = Categoria.objects.filter(torneo_id=torneo_id).values('id', 'nombre')
        print(categorias)  # Para verificar qué categorías se obtienen
        return JsonResponse({'categorias': list(categorias)})
    except Exception as e:
        print(f"Error al obtener categorías: {e}")  # Para ver cualquier error
        return JsonResponse({'error': str(e)}, status=500)


def fetch_equipos(request, categoria_id):
    # Filtrar los equipos relacionados con la categoría especificada
    try:
        equipos = Equipo.objects.filter(categoria_equipos__categoria_id=categoria_id).values('id', 'nombre')
        print(equipos)
        return JsonResponse({'equipos': list(equipos)})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


    print(f"Torneo seleccionado:")
    if request.method == 'POST':
        # Solicitud POST: Procesar el formulario
        print("Solicitud POST recibida")
        print(request.POST)
        torneo_id = request.POST.get('torneo')
        print(f"Torneo seleccionado: {torneo_id}")
        categoria_id = request.POST.get('categoria')
        equipo_id = request.POST.get('equipo')

        # Obtener la persona y el jugador
        persona = get_object_or_404(Persona, profile=request.user.profile)
        jugador = Jugador.objects.get(persona=persona)

        # Obtener la instancia de CategoriaEquipo
        categoria_equipo = get_object_or_404(CategoriaEquipo, categoria_id=categoria_id, equipo_id=equipo_id)

        # Crear la asociación en el modelo JugadorCategoriaEquipo
        JugadorCategoriaEquipo.objects.create(
            jugador=jugador,
            categoria_equipo=categoria_equipo  # Cambiado a la instancia de CategoriaEquipo
        )

        # Redirigir o mostrar un mensaje de éxito
        return redirect('registro_exitoso')  # O la URL a la que quieras redirigir

    else:
        # Solicitud GET: Cargar torneos y renderizar el formulario
        torneos = Torneo.objects.all()
        print(torneos)
        return render(request, 'persona/seleccionar_categoria_equipo.html', {'torneos': torneos})


def seleccionar_categoria_equipo(request):
    if request.method == 'POST':
        # Solicitud POST: Procesar el formulario
        print("Solicitud POST recibida")
        print(request.POST)

        torneo_id = request.POST.get('torneo')
        print(f"Torneo seleccionado: {torneo_id}")
        categoria_id = request.POST.get('categoria')
        equipo_id = request.POST.get('equipo')

        try:
            # Obtener la persona asociada al perfil del usuario
            persona = get_object_or_404(Persona, profile=request.user.profile)
            
            # Obtener el jugador asociado a esa persona
            jugador = get_object_or_404(Jugador, persona=persona)
            print(f"Jugador encontrado: {jugador.id}")
            
            # Obtener la instancia de CategoriaEquipo
            categoria_equipo = get_object_or_404(CategoriaEquipo, categoria_id=categoria_id, equipo_id=equipo_id)
            print(f"Categoría-Equipo encontrada: {categoria_equipo.id}")
            # Crear la asociación en el modelo JugadorCategoriaEquipo
            JugadorCategoriaEquipo.objects.create(
                jugador=jugador,
                categoria_equipo=categoria_equipo
            )

            # Redirigir o mostrar un mensaje de éxito
            return redirect('menu_jugador')  # O la URL a la que quieras redirigir

        except Jugador.DoesNotExist:
            print("Error: El jugador no existe para la persona.")
            return redirect('home')  # Redirige a una página de error o mostrar un mensaje adecuado
        except CategoriaEquipo.DoesNotExist:
            print("Error: La categoría o equipo no existe.")
            return redirect('home')  # Redirige a una página de error o mostrar un mensaje adecuado
        except IntegrityError as e:
            print(f"Error de integridad (clave foránea fallida): {e}")
            return redirect('home')  # Redirige a una página de error o mostrar un mensaje adecuado
        except Exception as e:
            print(f"Otro error ocurrió: {e}")
            return redirect('home')  # Redirige a una página de error o mostrar un mensaje adecuado

    else:
        # Solicitud GET: Cargar torneos y renderizar el formulario
        torneos = Torneo.objects.all()
        print("Torneos disponibles:", torneos)
        return render(request, 'persona/seleccionar_categoria_equipo.html', {'torneos': torneos})


def error_registro(request):
    return render(request, 'persona/error_registro.html')


@login_required
@never_cache
def menu_jugador(request):
    # Obtener el perfil del usuario logueado
    profile = request.user.profile

    # Intentar obtener la Persona asociada al profile del usuario
    try:
        persona = Persona.objects.get(profile=profile)
        jugador = Jugador.objects.get(persona=persona)
    except Persona.DoesNotExist:
        return redirect('registrar_persona')
    except Jugador.DoesNotExist:
        return redirect('registrar_jugador')

    # Obtener la ficha médica del jugador
    try:
        ficha_medica = RegistroMedico.objects.get(jugador=jugador)
    except RegistroMedico.DoesNotExist:
        ficha_medica = None  # O maneja según lo que desees

    # Obtener los antecedentes usando la ficha médica
    antecedentes = AntecedenteEnfermedades.objects.filter(idfichaMedica=ficha_medica)

    # Obtener las categorías, equipos y torneos relacionados al jugador
    jugador_categoria_equipos = JugadorCategoriaEquipo.objects.select_related(
        'categoria_equipo__categoria__torneo',
        'categoria_equipo__equipo'
    ).filter(jugador=jugador)

    # Crear una estructura para almacenar la información del jugador, categorías, equipos y torneos
    jugador_info = {
        'nombre': jugador.persona.profile.nombre,
        'apellido': jugador.persona.profile.apellido,
        'direccion': jugador.persona.direccion,
        'telefono': jugador.persona.telefono,
        'grupo_sanguineo': jugador.grupo_sanguineo,
        'cobertura_medica': jugador.cobertura_medica,
        'numero_afiliado': jugador.numero_afiliado,
        'categorias_equipo': []
    }

FichaMedica/persona/templates/persona/dashboard_jugador.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Salud - Aptos Físicos{% endblock %}

{% block content %}
<style>
  body {
      background-image: url("{% static 'img/background.jpg' %}");
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center;
      height: 100vh;
      margin: 0;
      position: relative;
      font-family: 'Arial', sans-serif;
  }

  body::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(255, 255, 255, 0.8);
      z-index: -1;
  }

  .form-wrapper {
      max-width: 800px;
      margin: 50px auto;
      background-color: #fff;
      padding: 40px;
      border-radius: 10px;
      box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);
  }

  .form-wrapper h1 {
      font-size: 2rem;
      color: #343a40;
      margin-bottom: 40px;
  }

  .info-card {
      background-color: #f8f9fa;
      border: 1px solid #dee2e6;
      border-radius: 8px;
      padding: 15px;
      margin-bottom: 20px;
      text-align: left;
      transition: transform 0.3s, box-shadow 0.3s;
  }

  .info-card:hover {
      transform: translateY(-5px);
      box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2);
  }

  .info-card h3 {
      font-size: 1.5rem;
      color: #495057;
      margin-bottom: 10px;
  }

  .info-card p {
      font-size: 1rem;
      color: #6c757d;
      margin: 0;
  }

  .info-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
  }

  .welcome-message {
      text-align: center;
      margin-bottom: 40px;
  }

  .welcome-message h1 {
      font-size: 2.5rem;
      color: #007bff;
      font-weight: bold;
  }

  .welcome-message h2 {
      padding: 20px;
      font-size: 1.5rem;
      color: #6c757d;
  }

  @media (max-width: 768px) {
      .info-grid {
          grid-template-columns: 1fr;
      }
  }
</style>

<main class="main">
  <div class="welcome-message">
    <h1>Bienvenido/a, {{ profile.nombre }} {{ profile.apellido }}</h1>
    <h2>Información del perfil</h2>
  </div>

  <div class="form-wrapper">
    <div class="info-grid">
      <!-- Información personal -->
      <div class="info-card">
        <h3>Datos Personales</h3>
        <p><strong>Nombre:</strong> {{ profile.nombre }}</p>
        <p><strong>Apellido:</strong> {{ profile.apellido }}</p>
        <p><strong>DNI:</strong> {{ profile.dni }}</p>
        <p><strong>Fecha de Nacimiento:</strong> {{ profile.fecha_nacimiento }}</p>
      </div>

      <!-- Información de contacto -->
      <div class="info-card">
        <h3>Contacto</h3>
        <p><strong>Email:</strong> {{ profile.email }}</p>
        <p><strong>Teléfono:</strong> {{ persona.telefono }}</p>
        <p><strong>Teléfono Alternativo:</strong> {{ persona.telefono_alternativo }}</p>
        <p><strong>Dirección:</strong> {{ persona.direccion }}</p>
      </div>

      <!-- Información de salud -->
      <div class="info-card">
        <h3>Información de Salud</h3>
        <p><strong>Grupo Sanguíneo:</strong> {{ jugador.grupo_sanguineo }}</p>
        <p><strong>Obra Social:</strong> {{ jugador.cobertura_medica }}</p>
        <p><strong>Número de Afiliado:</strong> {{ jugador.numero_afiliado }}</p>
      </div>

      <!-- Información del torneo -->
      <div class="info-card">
        <h3>Torneo</h3>
        <p><strong>Nombre del Torneo:</strong> {{ jugador.jugadorcategoriaequipo_set.all.0.categoria_equipo.categoria.torneo.nombre }}</p>
        <p><strong>Categoría:</strong> {{ jugador.jugadorcategoriaequipo_set.all.0.categoria_equipo.categoria.nombre }}</p>
        <p><strong>Equipo:</strong> {{ jugador.jugadorcategoriaequipo_set.all.0.categoria_equipo.equipo.nombre }}</p>
      </div>

      <!-- Información de antecedentes de enfermedades -->
      <div class="info-card">
        <h3>Antecedentes de Enfermedades</h3>
        {% if antecedentes %}
            <ul>
                {% for antecedente in antecedentes %}
                    <li>
                        <strong>Fue Operado:</strong> {{ antecedente.fue_operado|yesno:"Sí,No" }}<br>
                        <strong>Toma Medicación:</strong> {{ antecedente.toma_medicacion|yesno:"Sí,No" }}<br>
                        <strong>Estuvo Internado:</strong> {{ antecedente.estuvo_internado|yesno:"Sí,No" }}<br>
                        <strong>Sufre Hormigueos:</strong> {{ antecedente.sufre_hormigueos|yesno:"Sí,No" }}<br>
                        <strong>Es Diabético:</strong> {{ antecedente.es_diabetico|yesno:"Sí,No" }}<br>
                        <strong>Es Asmático:</strong> {{ antecedente.es_amatico|yesno:"Sí,No" }}<br>
                        <strong>Es Alérgico:</strong> {{ antecedente.es_alergico|yesno:"Sí,No" }}<br>
                        <strong>Observaciones de Alergia:</strong> {{ antecedente.alerg_observ }}<br>
                        <strong>Antecedente de Epilepsia:</strong> {{ antecedente.antecedente_epilepsia|yesno:"Sí,No" }}<br>
                        <strong>Desviación de Columna:</strong> {{ antecedente.desviacion_columna|yesno:"Sí,No" }}<br>
                        <strong>Dolor de Cintura:</strong> {{ antecedente.dolor_cintira|yesno:"Sí,No" }}<br>
                        <strong>Fracturas:</strong> {{ antecedente.fracturas|yesno:"Sí,No" }}<br>
                        <strong>Dolores Articulares:</strong> {{ antecedente.dolores_articulares|yesno:"Sí,No" }}<br>
                        <strong>Falta de Aire:</strong> {{ antecedente.falta_aire|yesno:"Sí,No" }}<br>
                        <strong>Traumatismos Cráneo:</strong> {{ antecedente.tramatismos_craneo|yesno:"Sí,No" }}<br>
                        <strong>Dolor en el Pecho:</strong> {{ antecedente.dolor_pecho|yesno:"Sí,No" }}<br>
                        <strong>Pérdida de Conocimiento:</strong> {{ antecedente.perdida_conocimiento|yesno:"Sí,No" }}<br>
                        <strong>Presión Arterial:</strong> {{ antecedente.presion_arterial|yesno:"Sí,No" }}<br>
                        <strong>Muerte Súbita Familiar:</strong> {{ antecedente.muerte_subita_familiar|yesno:"Sí,No" }}<br>
                        <strong>Enfermedad Cardíaca Familiar:</strong> {{ antecedente.enfermedad_cardiaca_familiar|yesno:"Sí,No" }}<br>
                        <strong>Soplo Cardíaco:</strong> {{ antecedente.soplo_cardiaco|yesno:"Sí,No" }}<br>
                        <strong>Abstenerse de Competencia:</strong> {{ antecedente.abstenerce_competencia|yesno:"Sí,No" }}<br>
                        <strong>Antecedentes Coronarios Familiares:</strong> {{ antecedente.antecedentes_coronarios_familiares|yesno:"Sí,No" }}<br>
                        <strong>Fumar, Hipertensión, Diabetes:</strong> {{ antecedente.fumar_hipertension_diabetes|yesno:"Sí,No" }}<br>
                        <strong>Observación FHD:</strong> {{ antecedente.fhd_observacion }}<br>
                        <strong>Consumo de Cocaína/Anabólicos:</strong> {{ antecedente.consumo_cocaina_anabolicos|yesno:"Sí,No" }}<br>
                        <strong>Otra Información:</strong> {{ antecedente.otra_informacion }}<br>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No hay antecedentes registrados.</p>
        {% endif %}
      </div>
    </div>
  </div>
</main>
{% endblock %}

FichaMedica/persona/templates/persona/modificar_email.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="form-container">
        <h2>Cambiar Email</h2>
        <p>Email Registrado: {{ profile.email }}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Nuevo Email</label>
                <input type="email" id="email" name="email" required>
            </div>
            <button type="submit" class="btn">Cambiar Email</button>
        </form>
    </div>
{% endblock %}

FichaMedica/persona/templates/persona/modificar_perfil.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Modificar Perfil</h2>

    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}

        <div class="card mb-4">
            <div class="card-header">
                <h3>Datos Personales</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="id_telefono">Teléfono</label>
                        {{ form_persona.telefono }}  
                        {% if form_persona.telefono.errors %}
                            <div class="text-danger">
                                {{ form_persona.telefono.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_telefono_alternativo">Teléfono Alternativo</label>
                        {{ form_persona.telefono_alternativo }}  
                        {% if form_persona.telefono_alternativo.errors %}
                            <div class="text-danger">
                                {{ form_persona.telefono_alternativo.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 mb-3">
                        <label for="id_direccion">Dirección</label>
                        {{ form_persona.direccion }}  
                        {% if form_persona.direccion.errors %}
                            <div class="text-danger">
                                {{ form_persona.direccion.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <h3>Datos del Jugador</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="id_cobertura_medica">Cobertura Médica</label>
                        {% if form_jugador.cobertura_medica.value %}
                            {{ form_jugador.cobertura_medica }}
                        {% else %}
                            <input type="text" class="form-control" value="No Posee" readonly>
                        {% endif %}
                        {% if form_jugador.cobertura_medica.errors %}
                            <div class="text-danger">
                                {{ form_jugador.cobertura_medica.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_numero_afiliado">Número de Afiliado</label>
                        {% if form_jugador.numero_afiliado.value %}
                            {{ form_jugador.numero_afiliado }}
                        {% else %}
                            <input type="text" class="form-control" value="No Posee" readonly>
                        {% endif %}
                        {% if form_jugador.numero_afiliado.errors %}
                            <div class="text-danger">
                                {{ form_jugador.numero_afiliado.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        

        <div class="d-flex justify-content-between">
            <a href="{% url 'menu_jugador' %}" class="btn btn-secondary">Cancelar</a>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </div>
    </form>
</div>
{% endblock %}